### ISSUE TITLE
Play Queue Not Working

### ISSUE THREAD

**Issue by jonbongato** [zwand19/CordovaAppleMusic#4]
Hi, I was wondering if the playTrack method on your end is still functional? Do we enter the full iTunes URL as the first parameter or just the ID that you bolded in the documentation? Using the ID # at the end of the URL logs a success event, but I don't see the track queued in my Apple Music app.

**Comment by khevamann** [comment]
I am still wondering about this, did you figure it out?

**Comment by khevamann** [comment]
I have created a new plugin that fixes this issue and adds more support for apple music.
https://github.com/khevamann/CordovaAppleMusic
